apiVersion: v1
kind: Service
metadata:
  name: swagger-ui
  namespace: default
spec:
  selector:
    app: swagger
  type: ClusterIP    
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080